apiRules:
- include:
    uidRegex: ^DocFxForUnity
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- include:
    uidRegex: ^Data
    type: Namespace
- include:
    uidRegex: ^Utils
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace